const careers = [
  {
      "id": "natural_resources_director",
      "title": "Natural Resources Director",
      "duties": "Oversees management and administration of a Natural Resources Department and provides supervision and support to program managers within the NR Dept. Represents the tribe in policy forums, co-manager meetings, tribal council meetings and at meetings with other governments and organizations. Writes and reviews reports.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Project and people management skills",
      "education": "Generally bachelors or higher; sometimes associates+experience",
      "vector": [0.6, 0.8, 0.9, 0.7, 0.4],
      "categories": ["Directors and Leaders", "Policy, Planning, and Management"]
  },
  {
      "id": "habitat_manager",
      "title": "Habitat Restoration Program Manager",
      "duties": "Oversees habitat restoration projects managed by the tribe; write and manage grants; analyze data for reports; supervise staff",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Ability to work with others, including other tribes, and state and federal agencies; strong oral and writing skills, data analyzation",
      "education": "Bachelor's or higher",
      "vector": [0.7, 0.9, 0.6, 0.5, 0.4],
      "categories": ["Policy, Planning, and Management", "Conservation and Restoration"]
  },
  {
      "id": "hatchery_program_manager",
      "title": "Hatchery Program Manager",
      "duties": "Oversees operation and maintenance of hatchery and the successful production of salmon and steelhead, for the economic and cultural enrichment of the Tribe. Duties include capturing returning brood stock, raising fish and fry, monitor fish for signs of stress, development and implementation of feeding schedule.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Willingness to work nights and weekends as needed, ability to work independently; physical ability to work in various conditions including cold water",
      "education": "Associate's or Bachelor's Degree",
      "vector": [0.9, 0.7, 0.5, 0.6, 0.4],
      "categories": ["Policy, Planning, and Management", "Technicians and Field Support", "Conservation and Restoration"]
  },
  {
      "id": "shellfish_program_manager",
      "title": "Shellfish Program Manager",
      "duties": "The Shellfish Program Manager shall work with other technical staff to provide the expertise necessary for pre-season harvest planning and in season fishery management of sub-tidal Treaty-reserved shellfish resources.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Duties of the Shellfish Program Manager will involve participation in the development of annual species-specific management plans with the State of Washington, and in the construction and negotiation of intertribal sharing agreements.",
      "education": "Bachelor's or Master's degree",
      "vector": [0.8, 0.6, 0.7, 0.5, 0.3],
      "categories": ["Policy, Planning, and Management", "Scientific and Technical Specialists", "Conservation and Restoration"],
  },
  {
      "id": "environmental_planning_manager",
      "title": "Environmental Planning Manager",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.7, 0.8, 0.9, 0.6, 0.6],
      "categories": ["Policy, Planning, and Management", "Scientific and Technical Specialists"]
  },
  {
      "id": "fisheries_manager",
      "title": "Fisheries Manager",
      "duties": "Oversees fisheries program; oversees technical work that supports tribal fisheries. Supervisor to biologists and technicians; runs meetings, responsible for technical aspects of salmon harvest and stock assessment. Support policy staff in negotiating and managing the treaty salmon and steelhead resources. Interprets data collected from harvest. Write grants and budgets to support work within the Fisheries Department.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.9, 0.7, 0.6, 0.5, 0.4],
      "categories": ["Scientific and Technical Specialists", "Policy, Planning, and Management"]
  },
  {
      "id": "wildlife_manager",
      "title": "Wildlife Manager",
      "duties": "Provide professional scientific and management expertise to tribal staff and tribal leaders to support wildlife policy development and protection of treaty hunting rights. Responsibilities include planning and implementing field investigations, studies, and surveys of wildlife, applying population models and developing hunting regulations to ensure sustainable harvest.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Working knowledge of Microsoft Office, ArcGIS and statistical software. Experience with capturing and marking game animals. Experience with radio telemetry.",
      "education": "Bachelor's or Master's degree",
      "vector": [0.6, 0.9, 0.7, 0.5, 0.3],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Policy, Planning, and Management"],
  },
  {
      "id": "forestry_manager",
      "title": "Forestry Manager",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.5, 0.9, 0.8, 0.6, 0.4],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Policy, Planning, and Management"],
  },
  {
      "id": "policy_advisor",
      "title": "Policy Advisor",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.4, 0.6, 0.9, 0.7, 0.5],
      "categories": ["Policy, Planning, and Management", "Enforcement and Advocacy"],
  },
  {
      "id": "enhancement_manager",
      "title": "Enhancement Manager",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.7, 0.8, 0.6, 0.5, 0.4],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Policy, Planning, and Management"],
  },
  {
      "id": "watershed_and_land_use_team_leader",
      "title": "Watershed and Land Use Team Leader",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.8, 0.9, 0.6, 0.5, 0.4],
      "categories": ["Directors and Leaders", "Scientific and Technical Specialists", "Conservation and Restoration"],
  },
  {
      "id": "shellfish_farm_manager",
      "title": "Shellfish Farm Manager",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.9, 0.6, 0.7, 0.5, 0.3],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Policy, Planning, and Management"],
  },
  {
      "id": "water_quality_manager",
      "title": "Water Quality Manager",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.9, 0.7, 0.6, 0.5, 0.4],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Policy, Planning, and Management"],
  },
  {
      "id": "shellfish_biologist",
      "title": "Shellfish Biologist",
      "duties": "Assist Program Manager with all shellfish management activities. Perform stock assessments and assist with data analyses and harvest management; perform shellfish enhancement activities; assist with data collection related to shellfish projects, including shellfish tissue, water, sediment samples. supervise shellfish harvests and monitor harvesters.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Able to solve problems as they arise in the field, be able to identify species of interest to the study or survey for which the field work is taking place. Be a team worker and able to work independently when needed. PADI open water SCUBA diving certification required. Experience collecting scientific data while SCUBA diving an asset. Working knowledge of ArcGIS an asset.",
      "education": "Bachelor's or Master's; PADI/SCUBA certification",
      "vector": [0.8, 0.6, 0.7, 0.5, 0.4],
      "categories": ["Scientific and Technical Specialists", "Technicians and Field Support", "Conservation and Restoration"],
  },
  {
      "id": "environmental_biologist",
      "title": "Environmental Biologist",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.7, 0.8, 0.6, 0.5, 0.4],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Technicians and Field Support"],
  },
  {
      "id": "fisheries_finfish_salmon_biologist",
      "title": "Fisheries/Finfish/Salmon Biologist",
      "duties": "Works with natural resources personnel in the collection of commercial sampling data, spawning survey data, and other information necessary for the management of fisheries resources important to the Tribe.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Knowledge of current NW salmon stock management practices, understanding of tribal fishery management issues; demonstrated knowledge of riverine fisheries biology or hydrology with experience in salmon and steelhead stocks.",
      "education": "Bachelor's",
      "vector": [0.9, 0.7, 0.5, 0.6, 0.4],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Policy, Planning, and Management"],
  },
  {
      "id": "forest_and_fish_biologist",
      "title": "Forest and Fish Biologist",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.7, 0.9, 0.6, 0.5, 0.4],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Policy, Planning, and Management"],
  },
  {
      "id": "restoration_planner",
      "title": "Restoration Planner",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.8, 0.9, 0.6, 0.5, 0.3],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Policy, Planning, and Management"],
  },
  {
      "id": "watershed_planner_scientist",
      "title": "Watershed Planner/Scientist",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.8, 0.9, 0.6, 0.5, 0.4],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Policy, Planning, and Management"],
  },
  {
      "id": "restoration_ecologist",
      "title": "Restoration Ecologist",
      "duties": "Work on a team with other technical specialists to manage salmon habitat restoration planning, design, and construction projects that advance tribal objectives for salmon recovery.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Experience working in natural resources management, fisheries science, environmental engineering; project management skills for complex habitat projects; writing proposals/managing grants; understanding compliance with environmental permits.",
      "education": "Master's or Bachelor's",
      "vector": [0.7, 0.9, 0.6, 0.5, 0.4],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Policy, Planning, and Management"],
  },
  {
      "id": "climate_change_analyst",
      "title": "Climate Change Analyst",
      "duties": "The Climate Change Action Analyst will coordinate with staff on the development, integration and sharing of data documenting resource and environmental changes relative to climate change.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Experience working with Geographic Information Systems and managing and developing large databases is required. A working familiarity with climate change models, data and current literature is a plus.",
      "education": "Master's or Bachelor's",
      "vector": [0.6, 0.7, 0.8, 0.5, 0.7],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration"],
  },
  {
      "id": "project_biologist",
      "title": "Project Biologist",
      "duties": "The position requires the ability to express yourself clearly, persuasively, and produce technical writing understandable at non-technical levels.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Ability to take initiative and work independently while maintaining a teamwork attitude and effort",
      "education": "",
      "vector": [0.7, 0.8, 0.6, 0.5, 0.4],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Policy, Planning, and Management"],
  },
  {
      "id": "wildlife_biologist",
      "title": "Wildlife Biologist",
      "duties": "The Wildlife Biologist I position is expected to monitor wildlife populations and natural resource activities and practices within the traditional hunting areas.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Understanding of Endangered Species Act; principles and procedures of wildlife habitat management and biological research.",
      "education": "Bachelor's or Master's",
      "vector": [0.6, 0.9, 0.7, 0.5, 0.3],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Policy, Planning, and Management"],
  },
  {
      "id": "natural_resources_biologist",
      "title": "Natural Resources Biologist",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.7, 0.8, 0.7, 0.5, 0.4],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Policy, Planning, and Management"],
  },
  {
      "id": "environmental_fisheries_policy_analyst",
      "title": "Environmental/Fisheries Policy Analyst",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.6, 0.7, 0.9, 0.6, 0.5],
      "categories": ["Policy, Planning, and Management", "Enforcement and Advocacy", "Scientific and Technical Specialists"]
  },
  {
      "id": "groundfish_biologist",
      "title": "Groundfish Biologist",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.8, 0.7, 0.5, 0.5, 0.4],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Policy, Planning, and Management"],
  },
  {
      "id": "harvest_management_biologist",
      "title": "Harvest Management Biologist",
      "duties": "Oversees development of run size forecasts, preseason fishery planning and development of tribal fishing plans and regulations. Responsibilities during fisheries include coordination of catch accounting, catch reporting, biological sampling, and management of the fishery based on preseason and in-season updates. Post-fishery responsibilities include cooperative development of final catch accounting and reporting.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Knowledge of Pacific Northwest salmon and steelhead, knowledge of fisheries harvest management and techniques, software and data proficiency, technical writing skills, leadership and teamwork.",
      "education": "Bachelor's Degree, Master's Degree",
      "vector": [0.8, 0.7, 0.6, 0.5, 0.4],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Policy, Planning, and Management"],
  },
  {
      "id": "research_scientist",
      "title": "Research Scientist",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.6, 0.7, 0.6, 0.5, 0.8],
      "categories": ["Scientific and Technical Specialists"],
  },
  {
      "id": "air_quality_specialist",
      "title": "Air Quality Specialist",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.5, 0.7, 0.8, 0.5, 0.6],
      "categories": ["Scientific and Technical Specialists"],
  },
  {
      "id": "environmental_planner",
      "title": "Environmental Planner",
      "duties": "Provides policy & technical assistance for the habitat division. Works with government agencies to ensure projects have minimal impacts to aquatic and terrestrial resources of significance to the Tribe. Reviews and provides comments on government permit applications relevant to the use and management of aquatic and terrestrial resources.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Writing skills",
      "education": "Bachelor's degree, Master's degrees",
      "vector": [0.7, 0.8, 0.9, 0.6, 0.5],
      "categories": ["Conservation and Restoration", "Policy, Planning, and Management", "Enforcement and Advocacy"],
  },
  {
      "id": "restoration_biologist",
      "title": "Restoration Biologist",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.7, 0.9, 0.6, 0.5, 0.4],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration"],
  },
  {
      "id": "salmon_recovery_biologist",
      "title": "Salmon Recovery Biologist",
      "duties": "Participating in salmon and steelhead recovery efforts, Puget Sound restoration issues and activities, participating in recovery-related forums and workgroups, performing technical analysis of selected natural resource issues, and providing support in acquiring grants and in meeting grant administration requirements.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Knowledge of Word, Excel, writing and speaking skills, familiarity with state, federal, and local land use and environmental regulations, analysis data skills, understanding of research methods and techniques.",
      "education": "Master's degree",
      "vector": [0.9, 0.7, 0.6, 0.5, 0.4],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Policy, Planning, and Management"],
  },
  {
      "id": "habitat_biologist",
      "title": "Habitat Biologist",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.7, 0.9, 0.6, 0.5, 0.4],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Policy, Planning, and Management"],
  },
  {
      "id": "timber_fish_wildlife_biologist",
      "title": "Timber/Fish/Wildlife Biologist",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.6, 0.9, 0.7, 0.5, 0.3],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Policy, Planning, and Management"],
  },
  {
      "id": "stock_assessment_biologist",
      "title": "Stock Assessment Biologist",
      "duties": "Implement fishery-related research and monitoring programs/studies aimed at improving stock population forecasting, in-season management, and spawner escapement analysis. Assist other biologists in field data collections, data assessments, and analysis for the management of all Treaty Fishery Resources. Assist in the technical administration of grants, including developing proposals, implementing work plans, completing progress reports, coordinating and disseminating outputs from grants, and monitoring grant progress and budgets.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Working knowledge of Pacific Northwest Salmon and steelhead. Working knowledge of fisheries stock assessment techniques, experience collecting and managing fisheries data. Experience working with fishery sampling equipment including but not limited to electrofishing, screw traps, seine, fyke, and gill nets. Experience with statistical and other quantitative and/or analytical methods used to monitor and assess fisheries abundance and trends. Proficient in use of current software and data programs.",
      "education": "Bachelor's, Master's degrees",
      "vector": [0.9, 0.7, 0.5, 0.6, 0.4],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Policy, Planning, and Management", "Technicians and Field Support"],
  },
  {
      "id": "gis_specialist",
      "title": "GIS Specialist",
      "duties": "The Environmental GIS Analyst shall be responsible for developing and supporting the GIS capabilities of the program. The candidate will work cooperatively with appropriate staff to develop shoreline, watershed, and stream habitat analyses. The candidate will assist with the mapping and analysis for the Salmon and Steelhead Habitat Inventory and Analysis Program (SSHIAP) program, other habitat division needs, and work closely with other cultural and natural resources staff on specific projects.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Knowledge and experience with ESRI ArcGIS program is required; familiarity with other ArcGIS tools, remote sensing software, habitat modeling, writing and/or working with scripts is desired. Knowledge of GIS and GPS software and operation. Ability to manage large and small datasets for various projects. Ability to write and communicate effectively with various audiences is required. Knowledge of environmental issues, natural resource management practices, habitat classification systems, northwest salmon recovery planning and species conservation issues in western Washington is desired. Familiarity with salmon lifecycles and salmon habitat needs is also desired.",
      "education": "Bachelor's or Master's",
      "vector": [0.5, 0.6, 0.5, 0.4, 0.9],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration", "Policy, Planning, and Management"],
  },
  {
      "id": "freshwater_biologist",
      "title": "Freshwater Biologist",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.8, 0.8, 0.6, 0.5, 0.3],
      "categories": ["Scientific and Technical Specialists", "Conservation and Restoration"],
  },
  {
      "id": "wetland_specialist",
      "title": "Wetland Specialist",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.7, 0.9, 0.6, 0.5, 0.4],
      "categories": ["Scientific and Technical Specialists", "Technicians and Field Support"],
  },
  {
      "id": "hydrologist",
      "title": "Hydrologist",
      "duties": "Field work, office work, water rights discussions.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "Bachelor's, Master's degrees",
      "vector": [0.6, 0.7, 0.8, 0.5, 0.6],
      "categories": ["Scientific and Technical Specialists", "Technicians and Field Support", "Policy, Planning, and Management"],
  },
  {
      "id": "water_resources_specialist",
      "title": "Water Resources Specialist",
      "duties": "Support/conduct/hydrological, water quality, biological data collection/studies/reviews, carry out programs that support water rights; summarize data using data conversion, statistical procedures; provide technical review of documents and plans, write reports.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Familiarity with hydrogeology, hydrography, aquatic resources; field experience in streams, groundwater, surface water flow; computer skills, GIS, statistical software, manage multiple projects at once, excellent oral and written communication skills; problem-solving skills; understand and can apply environmental science standards.",
      "education": "Bachelor's, Master's degrees in hydrology, watershed studies, water resources management, environmental science",
      "vector": [0.9, 0.7, 0.6, 0.5, 0.4],
      "categories": ["Scientific and Technical Specialists", "Technicians and Field Support", "Policy, Planning, and Management"],
  },
  {
      "id": "invasive_species_coordinator",
      "title": "Invasive Species Coordinator",
      "duties": "Biologist focused on Aquatic Invasive Species (AIS) detection, impacts, and removal. Works with state co-managers and partners on removal efforts and rapid response. Assembles field gear, navigates to remote locations, sets traps, and operates aluminum boats and non-motorized watercraft. Conducts land-based and boat-based trapping assessments.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.7, 0.8, 0.6, 0.5, 0.3],
      "categories": ["Scientific and Technical Specialists", "Technicians and Field Support", "Policy, Planning, and Management"],
  },
  {
      "id": "natural_resources_technician",
      "title": "Natural Resources Technician",
      "duties": "Conduct field-based data collection, analysis and reporting using scientific principles; lead or assist with various field activities including surveys, studies, restoration and monitoring for fresh water and marine habitat, shellfish, fresh water and marine fish, water and sediment quality, vegetation, phytoplankton biotoxins, and habitat enhancement and restoration; maintain field equipment and supplies; provide technical support for development of data collection, surveys, reports.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Relevant experience in natural resources-related job; operate small boats; strong interpersonal, verbal and written communication skills; ability and desire to work outdoors, lift heavy items, willingness to work in suboptimal weather and at various times of the day or night; able to take initiative, work independently and balance project responsibilities.",
      "education": "High school diploma",
      "vector": [0.6, 0.8, 0.7, 0.5, 0.4],
      "categories": ["Technicians and Field Support"],
  },
  {
      "id": "fisheries_technician",
      "title": "Fisheries Technician",
      "duties": "Collect data from the field such as from smolt traps or beach seines; enter data into database, maintain gear needed to perform data collection, work hours can be unconventional (due to tides).",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Physically demanding work such as hiking, heavy lifting and carrying heavy weight, working in inclement weather conditions; ID fish and other animals; work with others well, knowledge of scientific methods and techniques for collecting data, work professionally with tribal technical staff; comfortable interacting with the public and other agency personnel.",
      "education": "Associate of Science degree",
      "vector": [0.9, 0.7, 0.6, 0.5, 0.4],
      "categories": ["Technicians and Field Support"],
  },
  {
      "id": "wildlife_technician",
      "title": "Wildlife Technician",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.6, 0.9, 0.7, 0.5, 0.3],
      "categories": ["Technicians and Field Support"],
  },
  {
      "id": "water_quality_technician",
      "title": "Water Quality Technician",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.9, 0.7, 0.6, 0.5, 0.4],
      "categories": ["Technicians and Field Support"],
  },
  {
      "id": "shellfish_technician",
      "title": "Shellfish Technician",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.8, 0.6, 0.7, 0.5, 0.4],
      "categories": ["Technicians and Field Support"],
  },
  {
      "id": "hatchery_technician",
      "title": "Hatchery Technician",
      "duties": "Assist with hatchery operations including spawning and rearing of salmon and maintenance of hatchery grounds and equipment. Egg picking, spawning adult salmon, collecting water and tissue samples.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Ability to operate small powerboats, chainsaws, and other power tools, good physical shape, able to lift 65+ pounds. Willing to work weekends and odd hours.",
      "education": "High-school diploma",
      "vector": [0.9, 0.7, 0.6, 0.5, 0.3],
      "categories": ["Technicians and Field Support"],
  },
  {
      "id": "monitors_geoduck_shellfish_fishery",
      "title": "Monitors (Geoduck, Shellfish, Fishery)",
      "duties": "Oversees compliance with State and Tribal regulations and ensures safety during a fishery, while also making sure participants adhere to all rules; verify tribal identities; weigh and record harvest amounts; ensure proper tagging/identification of resource and recording it properly; maintain compliance with WA Dept of Health requirements; responsive to emergencies on the scene. Usually part of other jobs such as a Natural Resources Technician.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "High-school diploma",
      "vector": [0.8, 0.7, 0.6, 0.5, 0.4],
      "categories": ["Scientific and Technical Specialists", "Technicians and Field Support", "Policy, Planning, and Management"],
  },
  {
      "id": "fish_hatchery_culturist",
      "title": "Fish/Hatchery Culturist",
      "duties": "ID and sort individual adult fish according to species, gender, maturity condition; remove and collect eggs and sperm for spawning, ID and remove weak or dead eggs; feed fish in rearing ponds or raceways; monitor fish behavior and record mortalities; help address repairs to buildings, docks, boats, net pens; maintain and operate hatchery systems that support fish health and growth; wear safety equipment; help biologists with sampling during fisheries and for coded wire tagging; assist in marking and tagging fish.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Some knowledge of fish species and gender identification, fish culture methods and techniques, math, scientific terminology and techniques, mechanical equipment repair, understanding of how hatcheries operate; ability to work odd hours and times of day due to field conditions; perform strenuous tasks; work outdoors in all weather conditions; use power tools, follow instructions; complete tasks assigned, gather and compile data; use sound judgment.",
      "education": "High school diploma",
      "vector": [0.9, 0.7, 0.5, 0.6, 0.4],
      "categories": ["Technicians and Field Support"],
  },
  {
      "id": "field_technicians",
      "title": "Field Technicians",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.7, 0.8, 0.6, 0.5, 0.4],
      "categories": ["Technicians and Field Support"],
  },
  {
      "id": "environmental_technician",
      "title": "Environmental Technician",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.7, 0.8, 0.6, 0.5, 0.5],
      "categories": ["Technicians and Field Support"],
  },
  {
      "id": "environmental_management_specialist",
      "title": "Environmental Management Specialist",
      "duties": "Leads the Tribal Response Program (TRP) and marine oil spill preparedness, prevention, and response. Coordinates property inventories and assessments, does public outreach, collaborates with Oil Spill Response Organizations, and oil spill response programs. Performs construction stormwater site inspections. Coordinates activities, program spending, grant management. Prepares technical reports and presentations.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "Bachelor's degree",
      "vector": [0.6, 0.8, 0.7, 0.5, 0.5],
      "categories": ["Scientific and Technical Specialists", "Technicians and Field Support", "Policy, Planning, and Management"],
  },
  {
      "id": "facilities_manager",
      "title": "Facilities Manager",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.5, 0.6, 0.8, 0.5, 0.6],
      "categories": ["Scientific and Technical Specialists", "Technicians and Field Support", "Policy, Planning, and Management"],
  },
  {
      "id": "field_crew_supervisor",
      "title": "Field Crew Supervisor",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.7, 0.8, 0.7, 0.5, 0.4],
      "categories": ["Technicians and Field Support", "Directors and Leaders"],
  },
  {
      "id": "natural_resources_enforcement_law_enforcement_officer",
      "title": "Natural Resources Enforcement/Law Enforcement Officer",
      "duties": "Natural Resource Enforcement Officers are specifically responsible to protect a tribe's natural resources through enforcement by patrolling, monitoring, and contacting members during harvesting efforts and closed season(s) to detect and/or prevent illegal harvest activities, in addition to upholding tribal codes, statutes and laws; providing emergency assistance to the public in a variety of situations; patrol; perform standard crime and accident prevention; ID and recover stolen property; investigate traffic accidents and crime; attend court for civil traffic and criminal cases; maintain and keep Natural Resources Enforcement equipment (vehicles, ATVs, trailers) in good repair.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Ability to analyze situations quickly and objectively, exercise good judgment to determine the proper course of action.",
      "education": "Basic Law Enforcement Academy",
      "vector": [0.4, 0.5, 0.9, 0.7, 0.3],
      "categories": ["Enforcement and Advocacy"]
  },
  {
      "id": "education_and_outreach_coordinator",
      "title": "Education and Outreach Coordinator",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.5, 0.6, 0.7, 0.9, 0.5],
      "categories": ["Outreach and Administrative Support", "Policy, Planning, and Management"]
  },
  {
      "id": "tribal_historic_preservation_officer",
      "title": "Tribal Historic Preservation Officer (THPO)",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.5, 0.6, 0.9, 0.8, 0.4],
      "categories": ["Outreach and Administrative Support", "Policy, Planning, and Management"]
  },
  {
      "id": "anthropologist",
      "title": "Anthropologist",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.4, 0.6, 0.8, 0.9, 0.5],
      "categories": ["Scientific and Technical Specialists", "Policy, Planning, and Management"]
  },
  {
      "id": "archaeologist",
      "title": "Archaeologist",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.4, 0.5, 0.8, 0.9, 0.5],
      "categories": ["Scientific and Technical Specialists", "Technicians and Field Support", "Policy, Planning, and Management"]
  },
  {
      "id": "wildlife_and_cultural_resources_director",
      "title": "Wildlife and Cultural Resources Director",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.6, 0.8, 0.9, 0.9, 0.4],
      "categories": ["Directors and Leaders", "Policy, Planning, and Management", "Conservation and Restoration"]
  },
  {
      "id": "community_outreach_volunteer_coordinator",
      "title": "Community Outreach / Volunteer Coordinator",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.5, 0.6, 0.7, 0.9, 0.5],
      "categories": ["Outreach and Administrative Support", "Policy, Planning, and Management"]
  },
  {
      "id": "natural_resources_attorney",
      "title": "Natural Resources Attorney",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.3, 0.4, 0.9, 0.8, 0.4],
      "categories": ["Enforcement and Advocacy", "Scientific and Technical Specialists", "Policy, Planning, and Management"]
  },
  {
      "id": "administrative_support",
      "title": "Administrative Support",
      "duties": "",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "",
      "education": "",
      "vector": [0.3, 0.4, 0.5, 0.6, 0.7],
      "categories": ["Outreach and Administrative Support", "Policy, Planning, and Management"],
  },
  {
      "id": "archivist",
      "title": "Archivist",
      "duties": "This position will manage and maintain the safekeeping of permanent records and historically valuable documents. The ideal candidate will have the skills to develop and maintain a records classification system to facilitate access to archival materials. This position will also assist in fulfilling related clerical duties.",
      "image": "/CareerPics/habitat_manager.png",
      "skills": "Experience in organizing large amounts of material in logical and accessible order. Knowledge of information technologies in an archival environment, including database management, records management, and creating digital libraries. Organized self-starter and creative problem solver with the ability to work collaboratively in a team environment. Demonstrated ability to communicate effectively, both verbally and in writing.",
      "education": "Bachelor's",
      "vector": [0.2, 0.3, 0.6, 0.8, 0.7],
      "categories": ["Scientific and Technical Specialists", "Outreach and Administrative Support", "Policy, Planning, and Management"],
  }
];

export default careers;


